// <auto-generated />
using System;
using LabReservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabReservation.Migrations
{
    [DbContext(typeof(LabReservationContext))]
    partial class LabReservationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("LabReservation.Models.Labinfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("tool_type")
                        .HasColumnType("TEXT");

                    b.Property<int>("update_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Labinfo");
                });

            modelBuilder.Entity("LabReservation.Models.Labstore", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("lad_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tool_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("update_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Labstore");
                });

            modelBuilder.Entity("LabReservation.Models.Reserve", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("TEXT");

                    b.Property<int>("store_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Reserve");
                });

            modelBuilder.Entity("LabReservation.Models.Toolinfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.Property<int>("update_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Toolinfo");
                });

            modelBuilder.Entity("LabReservation.Models.Userinfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("created_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .HasColumnType("TEXT");

                    b.Property<int>("update_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("update_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Userinfo");
                });
#pragma warning restore 612, 618
        }
    }
}
